# Generated by Django 3.2 on 2021-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='')),
                ('qualification', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('confirmpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
