# Generated by Django 3.2 on 2021-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='examhistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('questionsattended', models.IntegerField()),
                ('rightanswer', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='questionstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=3000)),
                ('optiona', models.CharField(max_length=300)),
                ('optionb', models.CharField(max_length=300)),
                ('optionc', models.CharField(max_length=300)),
                ('optiond', models.CharField(max_length=300)),
                ('correctanswer', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
            ],
        ),
    ]
