# Generated by Django 3.2 on 2021-04-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_examhistories_questionstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstable',
            name='questionid',
            field=models.IntegerField(max_length=30),
        ),
    ]
