# Generated by Django 3.2 on 2021-04-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_questionstable_questionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examhistories',
            name='percentage',
        ),
    ]
